### ISSUE TITLE
"host" network_mode is incompatible with port_bindings

### ISSUE THREAD

**Issue by willis936** [chriscrowe/docker-pihole-unbound#39]
HW: Raspberry pi 4B
distro: Dietpi 7.0.2

I checked that there are no port conflicts with `ss -tulpn`

stacktrace:
```
root@DietPi:~/docker/docker-pihole-unbound/one-container# docker-compose up -d
Creating volume "one-container_etc_pihole-unbound" with default driver
Creating volume "one-container_etc_pihole_dnsmasq-unbound" with default driver
Creating pihole ...

ERROR: for pihole  "host" network_mode is incompatible with port_bindings

ERROR: for pihole  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 80, in main
    command_func()
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 192, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python3.7/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 1165, in up
    to_attach = up(False)
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 1161, in up
    attach_dependencies=attach_dependencies,
  File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 702, in up
    get_deps,
  File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 106, in parallel_execute
    raise error_to_reraise
  File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 204, in producer
    result = func(obj)
  File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 688, in do
    override_options=override_options,
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 563, in execute_convergence_plan
    override_options=override_options
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 479, in _execute_convergence_create
    "Creating"
  File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 106, in parallel_execute
    raise error_to_reraise
  File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 204, in producer
    result = func(obj)
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 477, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 456, in create_and_start
    container = service.create_container(number=n, quiet=True)
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 333, in create_container
    previous_container=previous_container,
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 937, in _get_container_create_options
    one_off=one_off)
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 1069, in _get_container_host_config
    cpu_rt_runtime=options.get('cpu_rt_runtime'),
  File "/usr/local/lib/python3.7/dist-packages/docker/api/container.py", line 598, in create_host_config
    return HostConfig(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/docker/types/containers.py", line 339, in __init__
    'network_mode', 'host', 'port_bindings'
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
```

**Comment by willis936** [comment]
I did a fresh install of docker-compose and clone of this repo and am not able to recreate the issue.  I'm not sure what caused the issue.  I don't have much experience with containers.
